/**
 * MCP tool definition emitter.
 *
 * Emits one MCP tool per operation in the canonical IR. Each tool's
 * `inputSchema` is derived from the operation's request schema (when
 * available from Wave 2) — for operations without an OpenAPI schema
 * (like `/v1/systemone`), a minimal string-arg schema is emitted.
 *
 * Output: `src/generated/mcp/tools.json` — a single JSON file consumed
 * by `McpBridge.registerGeneratedOllamaTools()` (see
 * `src/mcp/generated-bridge.ts`).
 *
 * Tool naming convention: `ollama_<operationId>`. The `ollama_` prefix
 * prevents collisions with other MCP servers the host may have registered.
 *
 * Wave 6 scope: emit descriptors only. The actual tool execution path
 * (delegating to `OllamaRuntime.invoke`) is wired by the hand-written
 * `GeneratedOllamaTools` adapter in `src/mcp/generated-bridge.ts`.
 */
import type { JsonSchemaNode, OperationContract, SchemaContract } from '../../types.js';
import type { EmittedFile } from '../typescript/models.js';

const HEADER = '';

/** One MCP tool descriptor. */
export interface McpToolDescriptor {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
  readonly annotations?: {
    readonly title?: string;
    readonly readOnlyHint?: boolean;
    readonly destructiveHint?: boolean;
    readonly idempotentHint?: boolean;
    readonly openWorldHint?: boolean;
  };
  /** Internal: the operationId this tool wraps. Not part of the MCP spec. */
  readonly _operationId: string;
}

/** Emit `tools.json` containing every generated tool descriptor. */
export function emitMcpTools(
  outputDir: string,
  operations: readonly OperationContract[],
  schemas: readonly SchemaContract[],
): EmittedFile {
  const tools = buildToolDescriptors(operations, schemas);
  const data = {
    _comment:
      'AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT. Source: contracts/ir/ollama.ir.json.',
    tools: tools.map(({ _operationId, ...rest }) => ({
      ...rest,
      _operationId,
    })),
  };
  return {
    path: `${outputDir}/tools.json`,
    content: `${HEADER}${JSON.stringify(data, null, 2)}\n`,
  };
}

/** A minimal input schema for operations without an OpenAPI request schema. */
function fallbackInputSchema(op: OperationContract): Record<string, unknown> {
  return {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: `Input for ${op.id}` },
    },
    additionalProperties: true,
  };
}

/** Convert an IR schema definition into an MCP inputSchema (JSON Schema object). */
function schemaToInputSchema(
  schema: SchemaContract | undefined,
  allSchemas: Readonly<Map<string, SchemaContract>>,
): Record<string, unknown> | undefined {
  if (!schema?.definition) return undefined;
  return resolveRefs(schema.definition, allSchemas) as Record<string, unknown>;
}

/**
 * Recursively resolve `$ref` pointers against the schema lookup map so the
 * emitted JSON is self-contained (no external refs). MCP consumers shouldn't
 * have to fetch arbitrary `#/components/schemas/...` URIs.
 */
function resolveRefs(
  node: JsonSchemaNode,
  schemas: Readonly<Map<string, SchemaContract>>,
  seen = new Set<string>(),
): JsonSchemaNode {
  if (!node) return node;
  if (node.$ref) {
    const match = /#\/(?:components\/)?schemas\/(.+)$/.exec(node.$ref);
    const name = match?.[1];
    if (!name) return { description: `Unresolved $ref: ${node.$ref}` };
    if (seen.has(name)) {
      // Circular ref — emit a stub to avoid infinite recursion.
      return { description: `Circular ref to ${name}`, type: 'object' };
    }
    const target = schemas.get(name);
    if (!target?.definition) return { description: `Unresolved $ref: ${node.$ref}` };
    return resolveRefs(target.definition, schemas, new Set([...seen, name]));
  }
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === 'properties' && value && typeof value === 'object') {
      const props: Record<string, unknown> = {};
      for (const [propName, propSchema] of Object.entries(
        value as Record<string, JsonSchemaNode>,
      )) {
        props[propName] = resolveRefs(propSchema, schemas, seen);
      }
      result[key] = props;
    } else if (key === 'items' && value && typeof value === 'object') {
      result[key] = resolveRefs(value as JsonSchemaNode, schemas, seen);
    } else if (key === 'oneOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'anyOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'allOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'additionalProperties' && value && typeof value === 'object') {
      result[key] = resolveRefs(value as JsonSchemaNode, schemas, seen);
    } else {
      result[key] = value;
    }
  }
  return result as JsonSchemaNode;
}

/** Build a human-readable description from the operation's notes + path. */
function describeOperation(op: OperationContract): string {
  const summary = `Ollama ${op.method} ${op.path} (${op.domain} domain)`;
  if (!op.notes || op.notes.length === 0) return summary;
  return `${summary}\n\n${op.notes.map((n) => `- ${n}`).join('\n')}`;
}

/** Annotations: GET/HEAD = read-only, POST = potentially destructive. */
function annotationsFor(op: OperationContract): McpToolDescriptor['annotations'] {
  const isRead = op.method === 'GET' || op.method === 'HEAD';
  return {
    title: `${op.id} (Ollama)`,
    readOnlyHint: isRead,
    destructiveHint: op.method === 'DELETE',
    idempotentHint: op.method === 'GET' || op.method === 'HEAD',
    openWorldHint: false,
  };
}

/** Build the list of MCP tool descriptors from the IR. */
export function buildToolDescriptors(
  operations: readonly OperationContract[],
  schemas: readonly SchemaContract[],
): readonly McpToolDescriptor[] {
  const lookup = new Map(schemas.map((s) => [s.name, s] as const));
  return operations
    .filter((op) => op.status.documented)
    .map((op): McpToolDescriptor => {
      const reqRef = op.request?.$ref
        ?.replace(/^#\/schemas\//, '')
        .replace(/^#\/components\/schemas\//, '');
      const reqSchema = reqRef ? lookup.get(reqRef) : undefined;
      const inputSchema = schemaToInputSchema(reqSchema, lookup) ?? fallbackInputSchema(op);
      const annotations = annotationsFor(op);
      return {
        name: `ollama_${op.id}`,
        description: describeOperation(op),
        inputSchema,
        ...(annotations ? { annotations } : {}),
        _operationId: op.id,
      };
    });
}
