/**
 * MCP tool definition emitter.
 *
 * Emits one MCP tool per operation in the canonical IR. Each tool's
 * `inputSchema` is derived from the operation's request schema (when
 * available from Wave 2) — for operations without an OpenAPI schema
 * (like `/v1/systemone`), a minimal string-arg schema is emitted.
 *
 * Output: `src/generated/mcp/tools.json` — a single JSON file consumed
 * by `McpBridge.registerGeneratedOllamaTools()` (see
 * `src/mcp/generated-bridge.ts`).
 *
 * Tool naming convention: `ollama_<operationId>`. The `ollama_` prefix
 * prevents collisions with other MCP servers the host may have registered.
 *
 * Wave 6 scope: emit descriptors only. The actual tool execution path
 * (delegating to `OllamaRuntime.invoke`) is wired by the hand-written
 * `GeneratedOllamaTools` adapter in `src/mcp/generated-bridge.ts`.
 */
import type { JsonSchemaNode, OperationContract, OperationParameter, SchemaContract } from '../../types.js';
import type { EmittedFile } from '../typescript/models.js';

const HEADER = '';

/** One MCP tool descriptor. */
export interface McpToolDescriptor {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
  readonly annotations?: {
    readonly title?: string;
    readonly readOnlyHint?: boolean;
    readonly destructiveHint?: boolean;
    readonly idempotentHint?: boolean;
    readonly openWorldHint?: boolean;
  };
  /** Internal: the operationId this tool wraps. Not part of the MCP spec. */
  readonly _operationId: string;
}

/** Emit `tools.json` containing every generated tool descriptor. */
export function emitMcpTools(
  outputDir: string,
  operations: readonly OperationContract[],
  schemas: readonly SchemaContract[],
): EmittedFile {
  const tools = buildToolDescriptors(operations, schemas);
  const data = {
    _comment:
      'AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT. Source: contracts/ir/ollama.ir.json.',
    tools: tools.map(({ _operationId, ...rest }) => ({
      ...rest,
      _operationId,
    })),
  };
  return {
    path: `${outputDir}/tools.json`,
    content: `${HEADER}${JSON.stringify(data, null, 2)}\n`,
  };
}

/**
 * Wave 12 (P1 #5 + #8): derive an MCP input schema for operations that
 * don't have a request body schema. Previously the emitter fell back to
 * `{ prompt: string, additionalProperties: true }` — a fabricated,
 * non-contract-shaped schema that misled MCP consumers into thinking
 * every such operation takes a free-form prompt.
 *
 * The new fallback is structurally derived from the operation's
 * declared parameters (Wave 12 P1 #8 added these to the IR):
 *   - Path parameters become required string fields.
 *   - Operations with no parameters and no body (e.g. /api/version,
 *     /api/tags, /api/ps) get an empty object schema.
 *
 * Example: GET /v1/models/{model} →
 *   { type: 'object', properties: { model: { type: 'string' } },
 *     required: ['model'], additionalProperties: false }
 *
 * Example: GET /api/version →
 *   { type: 'object', properties: {}, additionalProperties: false }
 *
 * This is honest about what the operation actually accepts — the MCP
 * consumer can call the tool with the right shape immediately, without
 * having to read the Ollama docs to discover that the "prompt" field the
 * generator invented doesn't actually exist.
 *
 * Wave 12 P1 #8: the IR now carries `parameters` structurally. We
 * prefer that field when present (it's the canonical source) and fall
 * back to extracting from the path template for backwards compat with
 * any operation the normalizer hasn't yet enriched.
 */
function deriveInputSchemaFromPath(op: OperationContract): Record<string, unknown> {
  // Prefer the IR's structural parameters field when present.
  const params: readonly OperationParameter[] =
    op.parameters && op.parameters.length > 0
      ? op.parameters
      : extractPathParams(op.path).map(
          (name): OperationParameter => ({
            name,
            in: 'path',
            required: true,
            schema: { type: 'string' },
          }),
        );
  if (params.length === 0) {
    return {
      type: 'object',
      properties: {},
      additionalProperties: false,
      description: `${op.method} ${op.path} takes no request body.`,
    };
  }
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const p of params) {
    properties[p.name] = {
      ...(p.schema ?? { type: 'string' }),
      ...(p.description ? { description: p.description } : { description: `${p.in} parameter: ${p.name}` }),
    };
    if (p.required) required.push(p.name);
  }
  return {
    type: 'object',
    properties,
    ...(required.length > 0 ? { required } : {}),
    additionalProperties: false,
    description: `${op.method} ${op.path} — ${params.length} parameter${params.length === 1 ? '' : 's'}.`,
  };
}

/** Extract `{name}` segments from a path template like `/v1/models/{model}`. */
function extractPathParams(path: string): string[] {
  const matches = path.matchAll(/\{([^}]+)\}/g);
  const out: string[] = [];
  for (const m of matches) {
    if (m[1]) out.push(m[1]);
  }
  return out;
}

/** Convert an IR schema definition into an MCP inputSchema (JSON Schema object). */
function schemaToInputSchema(
  schema: SchemaContract | undefined,
  allSchemas: Readonly<Map<string, SchemaContract>>,
): Record<string, unknown> | undefined {
  if (!schema?.definition) return undefined;
  return resolveRefs(schema.definition, allSchemas) as Record<string, unknown>;
}

/**
 * Recursively resolve `$ref` pointers against the schema lookup map so the
 * emitted JSON is self-contained (no external refs). MCP consumers shouldn't
 * have to fetch arbitrary `#/components/schemas/...` URIs.
 */
function resolveRefs(
  node: JsonSchemaNode,
  schemas: Readonly<Map<string, SchemaContract>>,
  seen = new Set<string>(),
): JsonSchemaNode {
  if (!node) return node;
  if (node.$ref) {
    const match = /#\/(?:components\/)?schemas\/(.+)$/.exec(node.$ref);
    const name = match?.[1];
    if (!name) return { description: `Unresolved $ref: ${node.$ref}` };
    if (seen.has(name)) {
      // Circular ref — emit a stub to avoid infinite recursion.
      return { description: `Circular ref to ${name}`, type: 'object' };
    }
    const target = schemas.get(name);
    if (!target?.definition) return { description: `Unresolved $ref: ${node.$ref}` };
    return resolveRefs(target.definition, schemas, new Set([...seen, name]));
  }
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === 'properties' && value && typeof value === 'object') {
      const props: Record<string, unknown> = {};
      for (const [propName, propSchema] of Object.entries(
        value as Record<string, JsonSchemaNode>,
      )) {
        props[propName] = resolveRefs(propSchema, schemas, seen);
      }
      result[key] = props;
    } else if (key === 'items' && value && typeof value === 'object') {
      result[key] = resolveRefs(value as JsonSchemaNode, schemas, seen);
    } else if (key === 'oneOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'anyOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'allOf' && Array.isArray(value)) {
      result[key] = value.map((child) => resolveRefs(child as JsonSchemaNode, schemas, seen));
    } else if (key === 'additionalProperties' && value && typeof value === 'object') {
      result[key] = resolveRefs(value as JsonSchemaNode, schemas, seen);
    } else {
      result[key] = value;
    }
  }
  return result as JsonSchemaNode;
}

/** Build a human-readable description from the operation's notes + path. */
function describeOperation(op: OperationContract): string {
  const summary = `Ollama ${op.method} ${op.path} (${op.domain} domain)`;
  if (!op.notes || op.notes.length === 0) return summary;
  return `${summary}\n\n${op.notes.map((n) => `- ${n}`).join('\n')}`;
}

/** Annotations: GET/HEAD = read-only, POST = potentially destructive. */
function annotationsFor(op: OperationContract): McpToolDescriptor['annotations'] {
  const isRead = op.method === 'GET' || op.method === 'HEAD';
  return {
    title: `${op.id} (Ollama)`,
    readOnlyHint: isRead,
    destructiveHint: op.method === 'DELETE',
    idempotentHint: op.method === 'GET' || op.method === 'HEAD',
    openWorldHint: false,
  };
}

/**
 * Wave 17 (P0): operations excluded from generated MCP tools because they
 * require binary request bodies (application/octet-stream) that the
 * generated runtime's JSON-encoding path cannot handle. These operations
 * are in the IR for endpoint-discovery completeness and are accessible
 * via the hand-written OllamaClient methods (e.g. createBlob), but they
 * must not be advertised as executable MCP tools — that would mislead
 * MCP consumers into calling a tool that cannot actually perform the
 * operation.
 */
const BINARY_BODY_MCP_EXCLUSIONS = new Set(['createBlob']);

/** Build the list of MCP tool descriptors from the IR. */
export function buildToolDescriptors(
  operations: readonly OperationContract[],
  schemas: readonly SchemaContract[],
): readonly McpToolDescriptor[] {
  const lookup = new Map(schemas.map((s) => [s.name, s] as const));
  return operations
    .filter((op) => op.status.documented && !BINARY_BODY_MCP_EXCLUSIONS.has(op.id))
    .map((op): McpToolDescriptor => {
      const reqRef = op.request?.$ref
        ?.replace(/^#\/schemas\//, '')
        .replace(/^#\/components\/schemas\//, '');
      const reqSchema = reqRef ? lookup.get(reqRef) : undefined;
      // Wave 12 (P1 #5): when the operation has no request body schema,
      // derive the MCP input schema from the path (path params become
      // required string fields; parameterless GET/HEAD gets an empty
      // object). The previous `{ prompt: string }` fallback fabricated a
      // field the actual API doesn't accept.
      const inputSchema = schemaToInputSchema(reqSchema, lookup) ?? deriveInputSchemaFromPath(op);
      const annotations = annotationsFor(op);
      return {
        name: `ollama_${op.id}`,
        description: describeOperation(op),
        inputSchema,
        ...(annotations ? { annotations } : {}),
        _operationId: op.id,
      };
    });
}
