/**
 * Capability metadata emitter.
 *
 * Emits `src/generated/metadata/operations.json` — a single JSON file
 * containing the full operation contract metadata. Consumed by:
 *
 *   - `OllamaRuntime` (for environment support checks at request time)
 *   - `McpBridge` (for tool description generation)
 *   - The capabilities registry (for `contract.supports(...)` queries)
 *
 * Keeping this as JSON (rather than TS) lets non-TypeScript consumers (e.g.
 * the docs site, future MCP servers in other languages) read the same
 * metadata without a TypeScript compilation step.
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from '../typescript/models.js';

const HEADER =
  '// AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  '// Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n';

/** Emit a JSON metadata file containing every operation's full contract. */
export function emitMetadata(
  outputDir: string,
  operations: readonly OperationContract[],
): EmittedFile {
  const data = {
    operations: operations.map((op) => ({
      operationId: op.id,
      method: op.method,
      path: op.path,
      domain: op.domain,
      environment: op.environment,
      transport: op.transport,
      capabilities: op.capabilities,
      constraints: op.constraints ?? {},
      status: op.status,
      ...(op.notes ? { notes: op.notes } : {}),
    })),
  };
  const content = `${HEADER}\n${JSON.stringify(data, null, 2)}\n`;
  return { path: `${outputDir}/operations.json`, content };
}
