/**
 * API class emitter.
 *
 * Emits one TypeScript class per contract domain (native/openai/anthropic),
 * each containing one method per operation. The generated classes are thin:
 * they construct a {@link RequestDefinition} and delegate to
 * `OllamaRuntime.invoke()`. All transport, retry, streaming, telemetry
 * behavior lives in the hand-written runtime.
 *
 * Example output (for the `chat` operation):
 *
 * ```ts
 * export class NativeApi {
 *   constructor(private readonly runtime: OllamaRuntime) {}
 *
 *   chat(request: ChatRequest): Promise<ChatResponse>;
 *   chat(request: ChatRequest & { stream: true }): Promise<OllamaStream>;
 *   chat(request: ChatRequest): unknown {
 *     return this.runtime.invoke({ ...chat, body: request });
 *   }
 * }
 * ```
 *
 * The generated file imports:
 *   - `OllamaRuntime` from `../runtime/runtime.js`
 *   - The operation constants from `./operations.js`
 *   - The model types from `../models/index.js`
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * Each generated class delegates to OllamaRuntime — the runtime owns\n' +
  ' * transport, retry, streaming, telemetry, and error handling.\n' +
  ' */\n';

function pascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function schemaTypeFromRef(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/schemas\/(.+)$/.exec(ref) ?? /#\/components\/schemas\/(.+)$/.exec(ref);
  if (!match || !match[1]) return undefined;
  const name = match[1];
  const segments = name.split(/[^A-Za-z0-9]+/).filter((s) => s.length > 0);
  return segments.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
}

/** Emit a single method for one operation. */
function emitMethod(op: OperationContract): string {
  const reqType = schemaTypeFromRef(op.request?.$ref) ?? 'Record<string, unknown>';
  const resType = schemaTypeFromRef(op.response?.$ref) ?? 'unknown';
  const methodName = op.id;
  const streaming = op.transport.streaming;
  const streamingDefault = op.transport.streamingDefault ?? false;
  const hasBody =
    op.method === 'POST' || op.method === 'PUT' || op.method === 'PATCH' || op.method === 'DELETE';

  const lines: string[] = [];

  // Overload 1: explicit non-streaming
  if (streaming) {
    lines.push(`  ${methodName}(request: ${reqType} & { stream?: false }): Promise<${resType}>;`);
    // Overload 2: explicit streaming
    lines.push(
      `  ${methodName}(request: ${reqType} & { stream: true }): Promise<AsyncGenerator<${resType}, void, undefined>>;`,
    );
  }

  // Implementation signature
  const implReturn = streaming
    ? `Promise<${resType} | AsyncGenerator<${resType}, void, undefined>>`
    : `Promise<${resType}>`;

  // GET/HEAD methods don't take a request body — accept an optional
  // per-call options object instead.
  if (!hasBody) {
    lines.push(`  ${methodName}(options?: { signal?: AbortSignal }): ${implReturn} {`);
    lines.push(`    return this.runtime.invoke({`);
    lines.push(`      operation: ${op.id}Op,`);
    lines.push(`      body: undefined,`);
    lines.push(`      ...(options?.signal !== undefined ? { signal: options.signal } : {}),`);
    lines.push(`    });`);
    lines.push(`  }`);
    return lines.join('\n');
  }

  lines.push(`  ${methodName}(request: ${reqType}): ${implReturn} {`);
  lines.push(`    return this.runtime.invoke({`);
  lines.push(`      operation: ${op.id}Op,`);
  // If streaming is supported and the docs say the default is to stream,
  // leave the request's own `stream` field alone — the user can override
  // explicitly. We do NOT force `{ stream: true, ...request }` here because
  // that would silently clobber the user's choice. The runtime applies the
  // default when neither the request nor the overlay specifies one.
  if (streaming && streamingDefault) {
    lines.push(`      body: request,`);
    lines.push(`      streamingDefault: true,`);
  } else {
    lines.push(`      body: request,`);
  }
  lines.push(`    });`);
  lines.push(`  }`);

  return lines.join('\n');
}

/** Emit the per-domain API class file (e.g. `native-api.ts`). */
export function emitDomainApi(
  outputDir: string,
  domain: 'native' | 'openai' | 'anthropic',
  operations: readonly OperationContract[],
): EmittedFile | undefined {
  const domainOps = operations.filter((op) => op.domain === domain);
  if (domainOps.length === 0) return undefined;

  const className = `${pascal(domain)}Api`;
  const methods = domainOps.map(emitMethod).join('\n\n');
  // Import operation constants with their `Op` suffix to avoid collisions
  // with reserved words. The local alias also uses the `Op` suffix to
  // avoid reserved-word collisions in the import binding (e.g. `delete`
  // is reserved, so we can't write `deleteOp as delete`).
  const importSpecs = domainOps.map((op) => `${op.id}Op`).join(', ');

  // Collect model types referenced by these operations.
  const referencedTypes = new Set<string>();
  for (const op of domainOps) {
    const req = schemaTypeFromRef(op.request?.$ref);
    const res = schemaTypeFromRef(op.response?.$ref);
    if (req) referencedTypes.add(req);
    if (res) referencedTypes.add(res);
  }
  const modelImports =
    referencedTypes.size > 0
      ? `import type { ${[...referencedTypes].sort().join(', ')} } from '../models/index.js';`
      : '// No model types referenced.';

  const content =
    `${HEADER}\n` +
    `import type { OllamaRuntime } from '../runtime/runtime.js';\n` +
    `${modelImports}\n` +
    `import { ${importSpecs} } from './operations.js';\n\n` +
    `/**\n * Generated API surface for Ollama's ${domain} domain.\n * Each method delegates to {@link OllamaRuntime.invoke}.\n */\n` +
    `export class ${className} {\n` +
    `  constructor(private readonly runtime: OllamaRuntime) {}\n\n` +
    `${methods}\n}\n`;

  return { path: `${outputDir}/${domain}-api.ts`, content };
}

/** Emit all per-domain API classes + an index that re-exports them. */
export function emitApi(
  outputDir: string,
  operations: readonly OperationContract[],
): readonly EmittedFile[] {
  const files: EmittedFile[] = [];
  const domains: readonly ('native' | 'openai' | 'anthropic')[] = ['native', 'openai', 'anthropic'];
  const exported: string[] = [];
  for (const domain of domains) {
    const file = emitDomainApi(outputDir, domain, operations);
    if (file) {
      files.push(file);
      exported.push(`${pascal(domain)}Api`);
    }
  }
  const indexContent =
    `${HEADER}\n` +
    exported
      .map((cls) => `export { ${cls} } from './${cls.toLowerCase().slice(0, -2)}-api.js';`)
      .join('\n') +
    '\n';
  files.push({ path: `${outputDir}/index.ts`, content: indexContent });
  return files;
}
