/**
 * API class emitter.
 *
 * Emits one TypeScript class per contract domain (native/openai/anthropic),
 * each containing one method per operation. The generated classes are thin:
 * they construct a {@link RequestDefinition} and delegate to
 * `OllamaRuntime.invoke()`. All transport, retry, streaming, telemetry
 * behavior lives in the hand-written runtime.
 *
 * Example output (for the `chat` operation):
 *
 * ```ts
 * export class NativeApi {
 *   constructor(private readonly runtime: OllamaRuntime) {}
 *
 *   chat(request: ChatRequest): Promise<ChatResponse>;
 *   chat(request: ChatRequest & { stream: true }): Promise<OllamaStream>;
 *   chat(request: ChatRequest): unknown {
 *     return this.runtime.invoke({ ...chat, body: request });
 *   }
 * }
 * ```
 *
 * The generated file imports:
 *   - `OllamaRuntime` from `../runtime/runtime.js`
 *   - The operation constants from `./operations.js`
 *   - The model types from `../models/index.js`
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * Each generated class delegates to OllamaRuntime — the runtime owns\n' +
  ' * transport, retry, streaming, telemetry, and error handling.\n' +
  ' */\n';

function pascal(name: string): string {
  // Capitalize the first letter; preserve the rest. For acronyms (openai,
  // anthropic) we want `OpenAI` and `Anthropic` (not `Openai` or `Anthropic`
  // with mixed casing). The mapping below handles the three known domains.
  if (name === 'openai') return 'OpenAI';
  if (name === 'anthropic') return 'Anthropic';
  if (name === 'native') return 'Native';
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function schemaTypeFromRef(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/schemas\/(.+)$/.exec(ref) ?? /#\/components\/schemas\/(.+)$/.exec(ref);
  if (!match || !match[1]) return undefined;
  const name = match[1];
  const segments = name.split(/[^A-Za-z0-9]+/).filter((s) => s.length > 0);
  return segments.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
}

/**
 * Wave 12 (P0 #1): explicit type map for OpenAI/Anthropic compatibility
 * operations whose request/response/streaming types are richer than
 * anything the OpenAPI snapshot currently models. The IR has no schema
 * refs for these operations, so the generator previously fell back to
 * `Record<string, unknown>` / `Promise<unknown>` — losing all type
 * information at the generated surface.
 *
 * Each entry points at the hand-written types already exported from
 * `src/integrations/{openai,anthropic}.ts`. The import path is relative
 * to the generated file's directory (`src/generated/api/`), so it points
 * at `../../integrations/index.js`.
 *
 * When the IR eventually grows schema refs for these operations (Wave 12
 * P1 #8 — enrich the canonical IR with structural fields), this map can
 * shrink and the generator can fall back to schemaTypeFromRef(). For now
 * it's the explicit, honest source of truth.
 */
interface CompatTypeBinding {
  readonly request: string;
  readonly response: string;
  /** Used for the streaming overload's `AsyncGenerator<...>` element type. */
  readonly streamChunk: string;
}

const COMPAT_TYPE_MAP: Readonly<Record<string, CompatTypeBinding>> = {
  openaiChatCompletions: {
    request: 'OpenAIChatCompletionRequest',
    response: 'OpenAIChatCompletionResponse',
    streamChunk: 'OpenAIChatCompletionChunk',
  },
  openaiCompletions: {
    request: 'OpenAICompletionRequest',
    response: 'OpenAICompletionResponse',
    streamChunk: 'OpenAICompletionChunk',
  },
  openaiEmbeddings: {
    request: 'OpenAIEmbeddingRequest',
    response: 'OpenAIEmbeddingResponse',
    streamChunk: 'never',
  },
  openaiModels: {
    request: 'void',
    response: 'OpenAIListModelsResponse',
    streamChunk: 'never',
  },
  openaiModelsGetOne: {
    request: 'void',
    response: 'OpenAIModelItem',
    streamChunk: 'never',
  },
  openaiResponses: {
    request: 'OpenAIResponsesRequest',
    response: 'OpenAIResponsesResponse',
    streamChunk: 'OpenAIResponsesStreamEvent',
  },
  anthropicMessages: {
    request: 'AnthropicMessagesRequest',
    response: 'AnthropicMessagesResponse',
    streamChunk: 'AnthropicMessageStreamEvent',
  },
};

/** Emit a single method for one operation. */
function emitMethod(op: OperationContract): string {
  const compat = COMPAT_TYPE_MAP[op.id];
  const reqType =
    compat?.request ?? schemaTypeFromRef(op.request?.$ref) ?? 'Record<string, unknown>';
  const resType = compat?.response ?? schemaTypeFromRef(op.response?.$ref) ?? 'unknown';
  const streamChunkType = compat?.streamChunk ?? resType;
  const methodName = op.id;
  const streaming = op.transport.streaming;
  const streamingDefault = op.transport.streamingDefault ?? false;
  const hasBody =
    op.method === 'POST' || op.method === 'PUT' || op.method === 'PATCH' || op.method === 'DELETE';

  // Wave 15 (P0): extract path parameters from the operation's parameters
  // list. These become explicit method arguments before the request body
  // or options object.
  const pathParams = (op.parameters ?? []).filter((p) => p.in === 'path');
  const pathParamArgs = pathParams.map((p) => `${p.name}: string`);
  const pathParamObj =
    pathParams.length > 0 ? `{ ${pathParams.map((p) => p.name).join(', ')} }` : undefined;

  const lines: string[] = [];

  // Wave 12 (P0 #1): streaming overload now uses the streamChunk type.
  // Wave 15 (P0): if the operation has path parameters, they become
  // explicit arguments before the request body.
  if (streaming) {
    if (pathParamArgs.length > 0) {
      lines.push(
        `  ${methodName}(${pathParamArgs.join(', ')}, request: ${reqType} & { stream?: false }): Promise<${resType}>;`,
      );
      lines.push(
        `  ${methodName}(${pathParamArgs.join(', ')}, request: ${reqType} & { stream: true }): Promise<AsyncGenerator<${streamChunkType}, void, undefined>>;`,
      );
    } else {
      lines.push(`  ${methodName}(request: ${reqType} & { stream?: false }): Promise<${resType}>;`);
      lines.push(
        `  ${methodName}(request: ${reqType} & { stream: true }): Promise<AsyncGenerator<${streamChunkType}, void, undefined>>;`,
      );
    }
  }

  // Implementation signature
  const implReturn = streaming
    ? `Promise<${resType} | AsyncGenerator<${streamChunkType}, void, undefined>>`
    : `Promise<${resType}>`;

  // GET/HEAD methods don't take a request body — accept an optional
  // per-call options object instead. Wave 15: if the operation has path
  // parameters, they become explicit arguments before the options object.
  if (!hasBody) {
    if (pathParamArgs.length > 0) {
      lines.push(
        `  ${methodName}(${pathParamArgs.join(', ')}, options?: { signal?: AbortSignal }): ${implReturn} {`,
      );
      lines.push(`    return this.runtime.invoke({`);
      lines.push(`      operation: ${op.id}Op,`);
      lines.push(`      body: undefined,`);
      lines.push(`      pathParams: ${pathParamObj},`);
      lines.push(`      ...(options?.signal !== undefined ? { signal: options.signal } : {}),`);
      lines.push(`    });`);
      lines.push(`  }`);
    } else {
      lines.push(`  ${methodName}(options?: { signal?: AbortSignal }): ${implReturn} {`);
      lines.push(`    return this.runtime.invoke({`);
      lines.push(`      operation: ${op.id}Op,`);
      lines.push(`      body: undefined,`);
      lines.push(`      ...(options?.signal !== undefined ? { signal: options.signal } : {}),`);
      lines.push(`    });`);
      lines.push(`  }`);
    }
    return lines.join('\n');
  }

  // POST/PUT/PATCH/DELETE with body. Wave 15: if the operation has path
  // parameters, they become explicit arguments before the request body.
  if (pathParamArgs.length > 0) {
    lines.push(`  ${methodName}(${pathParamArgs.join(', ')}, request: ${reqType}): ${implReturn} {`);
    lines.push(`    return this.runtime.invoke({`);
    lines.push(`      operation: ${op.id}Op,`);
    lines.push(`      pathParams: ${pathParamObj},`);
  } else {
    lines.push(`  ${methodName}(request: ${reqType}): ${implReturn} {`);
    lines.push(`    return this.runtime.invoke({`);
    lines.push(`      operation: ${op.id}Op,`);
  }
  if (streaming && streamingDefault) {
    lines.push(`      body: request,`);
    lines.push(`      streamingDefault: true,`);
  } else {
    lines.push(`      body: request,`);
  }
  lines.push(`    });`);
  lines.push(`  }`);

  return lines.join('\n');
}

/** Emit the per-domain API class file (e.g. `native-api.ts`). */
export function emitDomainApi(
  outputDir: string,
  domain: 'native' | 'openai' | 'anthropic',
  operations: readonly OperationContract[],
): EmittedFile | undefined {
  // Wave 12 (P1 #7): skip operations that target a different host (web
  // search, web fetch — they live at https://ollama.com, not the local
  // Ollama server). These operations are declared in the IR for
  // visibility and MCP generation, but they cannot be invoked through
  // the generated NativeApi class because that class delegates to a
  // runtime bound to the local Ollama server. Callers must use
  // OllamaClient.webSearch / OllamaClient.webFetch instead, which spin
  // up a dedicated cloud HttpClient pointed at the right host.
  //
  // Wave 15: also skip operations that take a binary body (e.g.
  // createBlob — POST /api/blobs/{digest} with application/octet-stream).
  // The generated runtime JSON-encodes request bodies, so binary-body
  // operations are handled by the hand-written OllamaClient methods.
  // They're in the IR for endpoint-discovery completeness only.
  const BINARY_BODY_OPS = new Set(['createBlob']);
  const domainOps = operations.filter(
    (op) => op.domain === domain && !op.host && !BINARY_BODY_OPS.has(op.id),
  );
  if (domainOps.length === 0) return undefined;

  const className = `${pascal(domain)}Api`;
  const methods = domainOps.map(emitMethod).join('\n\n');
  // Import operation constants with their `Op` suffix to avoid collisions
  // with reserved words. The local alias also uses the `Op` suffix to
  // avoid reserved-word collisions in the import binding (e.g. `delete`
  // is reserved, so we can't write `deleteOp as delete`).
  const importSpecs = domainOps.map((op) => `${op.id}Op`).join(', ');

  // Collect model types referenced by these operations.
  const referencedTypes = new Set<string>();
  for (const op of domainOps) {
    const req = schemaTypeFromRef(op.request?.$ref);
    const res = schemaTypeFromRef(op.response?.$ref);
    if (req) referencedTypes.add(req);
    if (res) referencedTypes.add(res);
  }
  const modelImports =
    referencedTypes.size > 0
      ? `import type { ${[...referencedTypes].sort().join(', ')} } from '../models/index.js';`
      : '// No model types referenced.';

  // Wave 12 (P0 #1): collect compat type imports (from src/integrations/).
  // These are the rich hand-written types for OpenAI/Anthropic operations
  // whose IR schema refs are still missing. Each compat binding contributes
  // its request, response, and stream chunk type names.
  const compatTypes = new Set<string>();
  for (const op of domainOps) {
    const binding = COMPAT_TYPE_MAP[op.id];
    if (!binding) continue;
    if (binding.request !== 'void') compatTypes.add(binding.request);
    if (binding.response !== 'never') compatTypes.add(binding.response);
    if (binding.streamChunk !== 'never') compatTypes.add(binding.streamChunk);
  }
  const compatImports =
    compatTypes.size > 0
      ? `import type { ${[...compatTypes].sort().join(', ')} } from '../../integrations/index.js';`
      : '';

  const content =
    `${HEADER}\n` +
    `import type { OllamaRuntime } from '../runtime/runtime.js';\n` +
    `${modelImports}\n` +
    (compatImports ? `${compatImports}\n` : '') +
    `import { ${importSpecs} } from './operations.js';\n\n` +
    `/**\n * Generated API surface for Ollama's ${domain} domain.\n * Each method delegates to {@link OllamaRuntime.invoke}.\n */\n` +
    `export class ${className} {\n` +
    `  constructor(private readonly runtime: OllamaRuntime) {}\n\n` +
    `${methods}\n}\n`;

  return { path: `${outputDir}/${domain}-api.ts`, content };
}

/** Emit all per-domain API classes + an index that re-exports them. */
export function emitApi(
  outputDir: string,
  operations: readonly OperationContract[],
): readonly EmittedFile[] {
  const files: EmittedFile[] = [];
  const domains: readonly ('native' | 'openai' | 'anthropic')[] = ['native', 'openai', 'anthropic'];
  const exported: string[] = [];
  for (const domain of domains) {
    const file = emitDomainApi(outputDir, domain, operations);
    if (file) {
      files.push(file);
      exported.push(`${pascal(domain)}Api`);
    }
  }
  // Build an index that re-exports BOTH the API classes AND every operation
  // constant. The two were previously emitted to the same `index.ts` path
  // with one overwriting the other; combining them here ensures consumers
  // importing from `@nemesis-oss/ollama-sdk/generated/api` get the full
  // public surface in one import.
  const apiClassExports = exported
    .map((cls) => {
      // File names are `<domain>-api.ts` — derive the domain from the class
      // name (e.g. `NativeApi` -> `native`).
      const domainKey = cls.slice(0, -3).toLowerCase();
      return `export { ${cls} } from './${domainKey}-api.js';`;
    })
    .join('\n');
  const opExports = operations
    .map((op) => `export { ${op.id}Op as ${op.id} } from './operations.js';`)
    .join('\n');
  const indexContent =
    `${HEADER}\n` +
    `// Generated API classes (Wave 3):\n` +
    `${apiClassExports}\n\n` +
    `// Operation constants (Wave 3):\n` +
    `${opExports}\n` +
    `export { allOperations } from './operations.js';\n` +
    `export { type OperationDefinition } from '../runtime/operation-definition.js';\n`;
  files.push({ path: `${outputDir}/index.ts`, content: indexContent });
  return files;
}
