/**
 * TypeScript interface emitter.
 *
 * Converts each {@link SchemaContract} in the canonical IR into a TypeScript
 * interface, written to `src/generated/models/<name>.ts`. The emitter is a
 * pure data transformer — no I/O, no side effects — so it can be unit tested
 * in isolation and re-used by `cli.ts generate` and the drift detector.
 *
 * Design choices:
 *
 *   - All properties are emitted as `readonly`. The existing hand-written
 *     `src/types.ts` follows this convention; preserving it keeps the
 *     generated surface a drop-in alternative.
 *   - Optional fields (not in the schema's `required` list) get the
 *     `| undefined` suffix, mirroring `exactOptionalPropertyTypes: true`.
 *   - `$ref` is resolved by name; the emitter assumes the IR's `schemas`
 *     list contains every referenced schema. Unresolved refs emit a
 *     `unknown` placeholder with a `// TODO: unresolved $ref` comment so
 *     the drift detector can flag them.
 *   - `oneOf` → TypeScript union (`A | B`).
 *   - `anyOf` → TypeScript union (`A | B`).
 *   - `allOf` → TypeScript intersection (`A & B`).
 *   - `additionalProperties: true` → `[key: string]: unknown`.
 *   - `additionalProperties: <schema>` → `[key: string]: <type>`.
 *   - Schema names are converted to PascalCase for interface names;
 *     property names are kept verbatim (Ollama uses snake_case on the wire).
 */
import type { JsonSchemaNode, SchemaContract } from '../../types.js';

/** A single emitted TypeScript file's content + intended path. */
export interface EmittedFile {
  readonly path: string;
  readonly content: string;
}

/** Emitter configuration. */
export interface EmitterOptions {
  /** Header comment prepended to every emitted file. */
  readonly header?: string;
}

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * See ADR 0013 and ADR 0014 for the contract-first architecture.\n' +
  ' */\n';

function pascalCase(name: string): string {
  if (!name) return name;
  // Split on non-alphanumeric boundaries; capitalize each segment and join.
  const segments = name.split(/[^A-Za-z0-9]+/).filter((s) => s.length > 0);
  if (segments.length === 0) return name;
  return segments.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
}

function refName(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/components\/schemas\/(.+)$/.exec(ref) ?? /#\/schemas\/(.+)$/.exec(ref);
  return match?.[1];
}

interface EmissionContext {
  readonly schemas: Readonly<Map<string, SchemaContract>>;
  readonly indent: string;
}

function emitType(node: JsonSchemaNode | undefined, ctx: EmissionContext): string {
  if (!node) return 'unknown';

  if (node.$ref) {
    const name = refName(node.$ref);
    if (!name) return 'unknown';
    return pascalCase(name);
  }

  if (node.oneOf && node.oneOf.length > 0) {
    return node.oneOf.map((child) => emitType(child, ctx)).join(' | ');
  }
  if (node.anyOf && node.anyOf.length > 0) {
    return node.anyOf.map((child) => emitType(child, ctx)).join(' | ');
  }
  if (node.allOf && node.allOf.length > 0) {
    return node.allOf.map((child) => emitType(child, ctx)).join(' & ');
  }

  if (node.enum && node.enum.length > 0) {
    return node.enum
      .map((value) => {
        if (value === null) return 'null';
        if (typeof value === 'string') return `'${value.replace(/'/g, "\\'")}'`;
        return String(value);
      })
      .join(' | ');
  }

  const type = node.type;

  // Wave 13 fix: JSON Schema allows `type` to be an array (e.g.
  // `type: [string, "null"]` for a nullable string). Handle this by
  // emitting a TypeScript union of the individual types.
  if (Array.isArray(type)) {
    const members = type.map((t) => emitType({ ...node, type: t }, ctx));
    // Deduplicate (e.g. [string, "null"] → string | null).
    const unique = [...new Set(members)];
    return unique.length === 1 ? unique[0]! : unique.join(' | ');
  }

  switch (type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      // Emit `T[]` (not `readonly T[]`) when this is a primitive alias or
      // union member — `readonly` modifiers are only valid on direct array
      // type annotations, not inside unions. The `readonly` keyword on
      // interface properties (which is where arrays usually appear) is
      // added by emitInlineObject, not here.
      return node.items ? `${emitType(node.items, ctx)}[]` : 'unknown[]';
    case 'object':
      // `type: object` with no `properties` and no `additionalProperties`
      // is a free-form object — emit `Record<string, unknown>` rather than
      // the empty `{}` type which lint forbids.
      if (!node.properties && node.additionalProperties === undefined) {
        return 'Record<string, unknown>';
      }
      return emitInlineObject(node, ctx);
    case undefined:
      // Object-like schemas (with `properties`) often omit `type: object`.
      if (node.properties) return emitInlineObject(node, ctx);
      if (node.additionalProperties === true) return 'Record<string, unknown>';
      if (node.additionalProperties && typeof node.additionalProperties === 'object') {
        return `Record<string, ${emitType(node.additionalProperties, ctx)}>`;
      }
      return 'unknown';
    default: {
      // If we reach here, the type is a string variant we don't handle.
      // Array types are handled above before the switch.
      throw new Error(`Unhandled schema type: ${String(type)}`);
    }
  }
}

function emitInlineObject(node: JsonSchemaNode, ctx: EmissionContext): string {
  const props = node.properties ?? {};
  const required = new Set(node.required ?? []);
  const lines: string[] = ['{'];

  for (const [propName, propSchema] of Object.entries(props)) {
    const isRequired = required.has(propName);
    let baseType = emitType(propSchema, ctx);
    const isArrayType =
      propSchema.type === 'array' ||
      (!propSchema.type && Boolean(propSchema.items)) ||
      (Array.isArray(propSchema.type) && propSchema.type.includes('array'));
    if (isArrayType) {
      const itemType = propSchema.items ? emitType(propSchema.items, ctx) : 'unknown';
      const needsParens = itemType.includes(' | ') || itemType.includes(' & ');
      const arrayType = `readonly ${needsParens ? `(${itemType})` : itemType}[]`;
      baseType = Array.isArray(propSchema.type)
        ? [arrayType, ...propSchema.type.filter((t) => t !== 'array')].join(' | ')
        : arrayType;
    }
    const type = isRequired ? baseType : `${baseType} | undefined`;
    const desc = propSchema.description;
    if (desc) {
      lines.push(`${ctx.indent}/** ${desc} */`);
    }
    lines.push(`${ctx.indent}readonly ${propName}${isRequired ? '' : '?'}: ${type};`);
  }

  const addl = node.additionalProperties;
  if (addl === true) {
    lines.push(`${ctx.indent}[key: string]: unknown;`);
  } else if (addl && typeof addl === 'object') {
    lines.push(`${ctx.indent}[key: string]: ${emitType(addl, ctx)};`);
  }

  // Closing brace aligned with the opening brace's indentation level.
  const closingIndent = ctx.indent.slice(0, -2);
  lines.push(`${closingIndent}}`);
  return lines.join('\n');
}

function emitSchemaInterface(schema: SchemaContract, ctx: EmissionContext): string {
  const name = pascalCase(schema.name);
  const def = schema.definition;
  if (!def) {
    return `${HEADER}\nexport type ${name} = unknown;\n`;
  }

  // `allOf` schemas: emit a `type` alias intersecting the members (plus
  // local properties in the rare JSON-Schema merge case). `emitInlineObject`
  // only reads `properties`, so routing an allOf schema through the
  // interface path would silently drop the intersection — exactly what
  // `UsageBucket` (allOf[UsageMetrics, {from, until, partial?}]) needs.
  if (def.allOf && def.allOf.length > 0) {
    const members = def.allOf.map((child) => emitType(child, ctx));
    if (def.properties) members.push(emitInlineObject(def, { ...ctx, indent: '  ' }));
    const alias = members.join(' & ');
    const lines: string[] = [HEADER, ''];
    if (schema.description) lines.push(`/** ${schema.description} */`);
    lines.push(`export type ${name} = ${alias};`, '');
    return lines.join('\n');
  }

  // If the schema is just a primitive alias (no `properties` and a primitive type),
  // emit a `type` alias instead of an `interface`.
  if (!def.properties && (def.type || def.$ref || def.oneOf || def.anyOf || def.enum)) {
    const alias = emitType(def, ctx);
    const lines: string[] = [HEADER, ''];
    if (schema.description) lines.push(`/** ${schema.description} */`);
    lines.push(`export type ${name} = ${alias};`, '');
    return lines.join('\n');
  }

  const body = emitInlineObject(def, { ...ctx, indent: '  ' });
  const lines: string[] = [HEADER, ''];
  if (schema.description) lines.push(`/** ${schema.description} */`);
  lines.push(`export interface ${name} ${body}`, '');
  return lines.join('\n');
}

/**
 * Collect every $ref target name reachable from a schema node.
 * Used to know which sibling model files to import.
 */
function collectRefs(node: JsonSchemaNode | undefined, acc: Set<string>): void {
  if (!node) return;
  if (node.$ref) {
    const match =
      /#\/components\/schemas\/(.+)$/.exec(node.$ref) ?? /#\/schemas\/(.+)$/.exec(node.$ref);
    if (match?.[1]) acc.add(match[1]);
    return;
  }
  if (node.properties) {
    for (const prop of Object.values(node.properties)) collectRefs(prop, acc);
  }
  if (node.items) collectRefs(node.items, acc);
  if (node.oneOf) for (const child of node.oneOf) collectRefs(child, acc);
  if (node.anyOf) for (const child of node.anyOf) collectRefs(child, acc);
  if (node.allOf) for (const child of node.allOf) collectRefs(child, acc);
  if (node.additionalProperties && typeof node.additionalProperties === 'object') {
    collectRefs(node.additionalProperties as JsonSchemaNode, acc);
  }
}

/** Build the schema lookup map from an IR's `schemas` list. */
export function schemaLookup(schemas: readonly SchemaContract[]): Map<string, SchemaContract> {
  const map = new Map<string, SchemaContract>();
  for (const s of schemas) map.set(s.name, s);
  return map;
}

/** Emit a single schema to a string. Exposed for unit tests. */
export function emitSchema(schema: SchemaContract, allSchemas: readonly SchemaContract[]): string {
  return emitSchemaInterface(schema, { schemas: schemaLookup(allSchemas), indent: '  ' });
}

/** Emit every IR schema into the `src/generated/models/` tree. */
export function emitModels(
  outputDir: string,
  schemas: readonly SchemaContract[],
  options: EmitterOptions = {},
): readonly EmittedFile[] {
  const header = options.header ?? HEADER;
  const ctx: EmissionContext = { schemas: schemaLookup(schemas), indent: '  ' };
  const allNames = new Set(schemas.map((s) => s.name));
  const files: EmittedFile[] = [];
  for (const schema of schemas) {
    const name = pascalCase(schema.name);
    // Collect every $ref target reachable from this schema, then drop the
    // self-reference (if any) and any names not in the schemas list.
    const refs = new Set<string>();
    collectRefs(schema.definition, refs);
    const externalRefs = [...refs]
      .filter((ref) => ref !== schema.name && allNames.has(ref))
      .map((ref) => pascalCase(ref))
      .sort();
    const importBlock =
      externalRefs.length > 0
        ? `import type { ${externalRefs.join(', ')} } from './index.js';\n`
        : '';
    const rawContent = emitSchemaInterface(schema, ctx);
    // Inject the import block right after the header.
    const content = rawContent.replace(HEADER, `${header}${importBlock ? `\n${importBlock}` : ''}`);
    files.push({
      path: `${outputDir}/${name}.ts`,
      content,
    });
  }
  // Always emit an index file re-exporting every model.
  const exports = schemas
    .map((s) => pascalCase(s.name))
    .sort()
    .map((name) => `export type { ${name} } from './${name}.js';`)
    .join('\n');
  files.push({
    path: `${outputDir}/index.ts`,
    content: `${header}\n${exports}\n`,
  });
  return files;
}
