/**
 * Operation definition emitter.
 *
 * Emits `src/generated/api/operations.ts` — a single file containing one
 * `OperationDefinition` per operation in the canonical IR. The runtime
 * consumes these descriptors via {@link OllamaRuntime.invoke}.
 *
 * The emitted code is intentionally minimal data: it captures the contract
 * (operationId, method, path, transport, streaming default, environment
 * support, capability support) without any behavior. All behavior lives in
 * the hand-written `OllamaRuntime` (src/generated/runtime/runtime.ts), which
 * the generated API classes delegate to.
 *
 * This is the seam described in ADR 0014: generated code owns the "what";
 * runtime code owns the "how".
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * Each OperationDefinition captures what Ollama exposes; the runtime\n' +
  ' * in src/generated/runtime/runtime.ts captures how the SDK behaves.\n' +
  ' */\n';

function literal(value: string | number | boolean): string {
  if (typeof value === 'string') {
    // Escape backslashes and single quotes; wrap in single quotes.
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  }
  return String(value);
}

function emitOperation(op: OperationContract): string {
  // Append `Op` suffix to avoid collisions with reserved words like `delete`,
  // `continue`, `class`, `new`. The exported constant name is what the API
  // class imports — the user never sees these names directly.
  const constName = `${op.id}Op`;
  const env = `{ local: ${literal(op.environment.local)}, cloud: ${literal(op.environment.cloud)} }`;
  const transport =
    `{ mode: ${literal(op.transport.mode)}, streaming: ${literal(op.transport.streaming)}` +
    (op.transport.streamingDefault !== undefined
      ? `, streamingDefault: ${literal(op.transport.streamingDefault)}`
      : '') +
    ' }';
  const caps = Object.entries(op.capabilities)
    .map(([k, v]) => `${k}: ${literal(v)}`)
    .join(', ');
  const constraints =
    op.constraints === undefined
      ? 'undefined'
      : `{ ${[
          op.constraints.minOllamaVersion !== undefined
            ? `minOllamaVersion: ${literal(op.constraints.minOllamaVersion)}`
            : '',
          op.constraints.maxRequestBytes !== undefined
            ? `maxRequestBytes: ${literal(op.constraints.maxRequestBytes)}`
            : '',
          op.constraints.maxRequestBytesWithImages !== undefined
            ? `maxRequestBytesWithImages: ${literal(op.constraints.maxRequestBytesWithImages)}`
            : '',
        ]
          .filter((s) => s.length > 0)
          .join(', ')} }`;
  const status =
    `{ documented: ${literal(op.status.documented)}` +
    (op.status.deprecated !== undefined ? `, deprecated: ${literal(op.status.deprecated)}` : '') +
    (op.status.experimental !== undefined
      ? `, experimental: ${literal(op.status.experimental)}`
      : '') +
    '}';
  const request = op.request ? `{ $ref: ${literal(op.request.$ref)} }` : 'undefined';
  const response = op.response ? `{ $ref: ${literal(op.response.$ref)} }` : 'undefined';
  const notes =
    op.notes && op.notes.length > 0
      ? `[${op.notes.map((n) => literal(n)).join(', ')}]`
      : 'undefined';

  // Wave 15 (P0): emit parameters array if the operation has structural
  // path/query/header parameters. Each parameter is a plain object
  // matching the OperationParameter interface in operation-definition.ts.
  const params =
    op.parameters && op.parameters.length > 0
      ? `[${op.parameters
          .map(
            (p) => {
              const schemaType =
                p.schema?.type !== undefined
                  ? typeof p.schema.type === 'string'
                    ? p.schema.type
                    : Array.isArray(p.schema.type)
                      ? p.schema.type[0] ?? 'string'
                      : 'string'
                  : undefined;
              return `{ name: ${literal(p.name)}, in: ${literal(p.in)}, required: ${literal(p.required)}${schemaType !== undefined ? `, schema: { type: ${literal(schemaType)} }` : ''}${p.description !== undefined ? `, description: ${literal(p.description)}` : ''} }`;
            },
          )
          .join(', ')}]`
      : undefined;

  return [
    `export const ${constName} = {`,
    `  operationId: ${literal(op.id)},`,
    `  method: ${literal(op.method)},`,
    `  path: ${literal(op.path)},`,
    ...(op.request ? [`  request: ${request},`] : []),
    ...(op.response ? [`  response: ${response},`] : []),
    `  environment: ${env},`,
    ...(op.host ? [`  host: ${literal(op.host)},`] : []),
    ...(params ? [`  parameters: ${params},`] : []),
    `  transport: ${transport},`,
    `  capabilities: { ${caps} },`,
    ...(op.constraints ? [`  constraints: ${constraints},`] : []),
    `  status: ${status},`,
    `  domain: ${literal(op.domain)},`,
    ...(op.notes && op.notes.length > 0 ? [`  notes: ${notes},`] : []),
    `} as const satisfies OperationDefinition;`,
    '',
  ].join('\n');
}

/** Emit the operations.ts file containing every OperationDefinition. */
export function emitOperations(
  outputDir: string,
  operations: readonly OperationContract[],
): EmittedFile {
  const blocks = operations.map(emitOperation);
  const content =
    `${HEADER}\n` +
    `import type { OperationDefinition } from '../runtime/operation-definition.js';\n\n` +
    blocks.join('\n') +
    `\nexport const allOperations = [\n` +
    operations.map((op) => `  ${op.id}Op,`).join('\n') +
    `\n] as const;\n`;
  return { path: `${outputDir}/operations.ts`, content };
}

/** Emit an `index.ts` re-exporting every operation. */
export function emitOperationsIndex(
  outputDir: string,
  operations: readonly OperationContract[],
): EmittedFile {
  const lines = operations.map((op) => `export { ${op.id}Op as ${op.id} } from './operations.js';`);
  lines.push("export { allOperations } from './operations.js';");
  lines.push("export { type OperationDefinition } from '../runtime/operation-definition.js';");
  return {
    path: `${outputDir}/index.ts`,
    content: `${HEADER}\n${lines.join('\n')}\n`,
  };
}
