/**
 * Schema-registry emitter.
 *
 * Wave 12 (P1 #6): generates `src/generated/runtime/schema-registry.ts`
 * from the canonical IR. Previously this file was hand-maintained — every
 * time an overlay added a new operation with a request schema, the
 * maintainer had to remember to add a matching entry here, and the
 * runtime silently skipped validation when they forgot.
 *
 * The generated registry maps operationId → request Zod schema for every
 * operation whose IR entry carries `request.$ref`. Operations without a
 * request schema (GET/HEAD, OpenAI/Anthropic compat whose schema refs
 * are not yet in the IR) simply don't appear in the map — the runtime's
 * `getRequestSchema()` returns `undefined` for them and validation is
 * skipped, same as before.
 *
 * Output: `src/generated/runtime/schema-registry.ts`
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * Maps every operation whose IR entry carries `request.$ref` to its\n' +
  ' * generated Zod request schema. Consumed by OllamaRuntime when\n' +
  ' * `validateRequests: true` is set (see ADR 0020).\n' +
  ' */\n';

/** Convert a `$ref` like `#/schemas/Foo` or `#/components/schemas/Foo` to `Foo`. */
function schemaNameFromRef(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/schemas\/(.+)$/.exec(ref) ?? /#\/components\/schemas\/(.+)$/.exec(ref);
  return match?.[1];
}

/**
 * Emit the schema-registry TypeScript file.
 *
 * @param outputDir absolute or repo-relative path to `src/generated/runtime/`
 * @param operations the IR's operations list
 */
export function emitSchemaRegistry(
  outputDir: string,
  operations: readonly OperationContract[],
): EmittedFile {
  // Build the operationId → schemaName map for every operation that has
  // a request schema ref. We sort by operationId for deterministic output.
  const entries: ReadonlyArray<{ operationId: string; schemaName: string }> = operations
    .map((op) => {
      const schemaName = schemaNameFromRef(op.request?.$ref);
      return schemaName ? { operationId: op.id, schemaName } : null;
    })
    .filter((e): e is { operationId: string; schemaName: string } => e !== null)
    .sort((a, b) => a.operationId.localeCompare(b.operationId));

  // Collect unique schema names so we can emit a single import line per schema.
  const uniqueSchemas = [...new Set(entries.map((e) => e.schemaName))].sort();

  const importLines =
    uniqueSchemas.length > 0
      ? uniqueSchemas
          .map((name) => `import { ${name}Schema } from '../models/${name}.schema.js';`)
          .join('\n')
      : '// No operations with request schemas in the IR.';

  const mapEntries =
    entries.length > 0
      ? entries
          .map((e) => `  ${e.operationId}: ${e.schemaName}Schema,`)
          .join('\n')
      : '  // (empty — no operations carry a request schema ref)';

  const content =
    `${HEADER}\n` +
    `import type { z } from 'zod';\n` +
    `${importLines}\n\n` +
    `/**\n` +
    ` * Map from operationId → request schema. The runtime consults this\n` +
    ` * registry (via getRequestSchema) when \`validateRequests: true\` is\n` +
    ` * set on OllamaRuntime. Response schemas are intentionally NOT\n` +
    ` * registered here — see ADR 0020 for the rationale (response\n` +
    ` * validation would break on legitimate forward-compat extensions to\n` +
    ` * the wire format).\n` +
    ` *\n` +
    ` * Wave 12 (P1 #6): this file is now generated from the canonical IR.\n` +
    ` * Previously hand-maintained, which meant new operations could be\n` +
    ` * added to the IR without their schema being registered — silently\n` +
    ` * disabling request validation for those operations.\n` +
    ` */\n` +
    `export const requestSchemas: Readonly<Record<string, z.ZodType>> = {\n` +
    `${mapEntries}\n` +
    `};\n\n` +
    `/** Look up a request schema by operationId. Returns \`undefined\` if no schema exists. */\n` +
    `export function getRequestSchema(operationId: string): z.ZodType | undefined {\n` +
    `  return requestSchemas[operationId];\n` +
    `}\n`;

  return { path: `${outputDir}/schema-registry.ts`, content };
}
