/**
 * Schema-registry emitter.
 *
 * Wave 12 (P1 #6): generates `src/generated/runtime/schema-registry.ts`
 * from the canonical IR. Previously this file was hand-maintained — every
 * time an overlay added a new operation with a request schema, the
 * maintainer had to remember to add a matching entry here, and the
 * runtime silently skipped validation when they forgot.
 *
 * Wave 13: now also generates a `responseSchemas` map and a
 * `getResponseSchema` function for the opt-in `validateResponses`
 * runtime path.
 *
 * The generated registry maps operationId → request Zod schema for every
 * operation whose IR entry carries `request.$ref`, and operationId →
 * response Zod schema for every operation whose IR entry carries
 * `response.$ref`. Operations without a schema simply don't appear in
 * the maps — the runtime's lookup functions return `undefined` for them
 * and validation is skipped.
 *
 * Output: `src/generated/runtime/schema-registry.ts`
 */
import type { OperationContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '/**\n * AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  ' * Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  ' * Maps every operation whose IR entry carries `request.$ref` / `response.$ref`\n' +
  ' * to its generated Zod schema. Consumed by OllamaRuntime when\n' +
  ' * `validateRequests: true` / `validateResponses: true` is set (ADR 0020).\n' +
  ' */\n';

/** Convert a `$ref` like `#/schemas/Foo` or `#/components/schemas/Foo` to `Foo`. */
function schemaNameFromRef(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/schemas\/(.+)$/.exec(ref) ?? /#\/components\/schemas\/(.+)$/.exec(ref);
  return match?.[1];
}

/**
 * Emit the schema-registry TypeScript file.
 *
 * @param outputDir absolute or repo-relative path to `src/generated/runtime/`
 * @param operations the IR's operations list
 */
export function emitSchemaRegistry(
  outputDir: string,
  operations: readonly OperationContract[],
): EmittedFile {
  // Build request entries: operationId → request schema name.
  const requestEntries: ReadonlyArray<{ operationId: string; schemaName: string }> = operations
    .map((op) => {
      const schemaName = schemaNameFromRef(op.request?.$ref);
      return schemaName ? { operationId: op.id, schemaName } : null;
    })
    .filter((e): e is { operationId: string; schemaName: string } => e !== null)
    .sort((a, b) => a.operationId.localeCompare(b.operationId));

  // Build response entries: operationId → response schema name.
  const responseEntries: ReadonlyArray<{ operationId: string; schemaName: string }> = operations
    .map((op) => {
      const schemaName = schemaNameFromRef(op.response?.$ref);
      return schemaName ? { operationId: op.id, schemaName } : null;
    })
    .filter((e): e is { operationId: string; schemaName: string } => e !== null)
    .sort((a, b) => a.operationId.localeCompare(b.operationId));

  // Collect unique schema names across both request and response entries.
  const allEntries = [...requestEntries, ...responseEntries];
  const uniqueSchemas = [...new Set(allEntries.map((e) => e.schemaName))].sort();

  const importLines =
    uniqueSchemas.length > 0
      ? uniqueSchemas
          .map((name) => `import { ${name}Schema } from '../models/${name}.schema.js';`)
          .join('\n')
      : '// No operations with request/response schemas in the IR.';

  const requestMapEntries =
    requestEntries.length > 0
      ? requestEntries
          .map((e) => `  ${e.operationId}: ${e.schemaName}Schema,`)
          .join('\n')
      : '  // (empty — no operations carry a request schema ref)';

  const responseMapEntries =
    responseEntries.length > 0
      ? responseEntries
          .map((e) => `  ${e.operationId}: ${e.schemaName}Schema,`)
          .join('\n')
      : '  // (empty — no operations carry a response schema ref)';

  const content =
    `${HEADER}\n` +
    `import type { z } from 'zod';\n` +
    `${importLines}\n\n` +
    `/**\n` +
    ` * Map from operationId → request schema. The runtime consults this\n` +
    ` * registry (via getRequestSchema) when \`validateRequests: true\` is\n` +
    ` * set on OllamaRuntime.\n` +
    ` *\n` +
    ` * Wave 12 (P1 #6): this file is now generated from the canonical IR.\n` +
    ` */\n` +
    `export const requestSchemas: Readonly<Record<string, z.ZodType>> = {\n` +
    `${requestMapEntries}\n` +
    `};\n\n` +
    `/**\n` +
    ` * Map from operationId → response schema. The runtime consults this\n` +
    ` * registry (via getResponseSchema) when \`validateResponses: true\` is\n` +
    ` * set on OllamaRuntime. Wave 13 added this map for operations where\n` +
    ` * typed response semantics are critical (e.g. System One).\n` +
    ` */\n` +
    `export const responseSchemas: Readonly<Record<string, z.ZodType>> = {\n` +
    `${responseMapEntries}\n` +
    `};\n\n` +
    `/** Look up a request schema by operationId. Returns \`undefined\` if no schema exists. */\n` +
    `export function getRequestSchema(operationId: string): z.ZodType | undefined {\n` +
    `  return requestSchemas[operationId];\n` +
    `}\n\n` +
    `/** Look up a response schema by operationId. Returns \`undefined\` if no schema exists. */\n` +
    `export function getResponseSchema(operationId: string): z.ZodType | undefined {\n` +
    `  return responseSchemas[operationId];\n` +
    `}\n`;

  return { path: `${outputDir}/schema-registry.ts`, content };
}
