/**
 * Zod schema emitter.
 *
 * Emits one Zod schema per IR schema, written to
 * `src/generated/models/<name>.schema.ts`. Each file exports
 * `<name>Schema` — a `z.ZodType` that parses the same shape as the
 * generated TypeScript interface.
 *
 * Output is paired with the TypeScript model emitters — every schema
 * has both a `ChatRequest.ts` (interface) and a `ChatRequest.schema.ts`
 * (Zod schema), with the same property names and types.
 *
 * Design choices:
 *
 *   - Optional fields (not in `required`) get `.optional()`.
 *   - `oneOf` → `z.union([...])`.
 *   - `anyOf` → `z.union([...])` (Zod has no any-of).
 *   - `allOf` → `z.intersection(...)` (rare in Ollama spec).
 *   - `$ref` → references the sibling schema by name (assumes the
 *     emitter has emitted that schema's file too).
 *   - `additionalProperties: true` → `.catchall(z.unknown())`.
 *   - `additionalProperties: <schema>` → `.catchall(<schema>)`.
 *   - `enum` → `z.enum([...])` for string literals, `z.literal(...)` union
 *     otherwise.
 *
 * Wave 9 scope: emit per-schema Zod files + an index. Runtime validation
 * (request pre-flight, response shape checks) is the consumer's
 * responsibility — wiring Zod into `OllamaRuntime.invoke` is a future
 * iteration.
 */
import type { JsonSchemaNode, SchemaContract } from '../../types.js';
import type { EmittedFile } from './models.js';

const HEADER =
  '// AUTO-GENERATED by `npm run contract:generate`. DO NOT EDIT.\n' +
  '// Source: contracts/ir/ollama.ir.json (canonical Ollama IR).\n' +
  '// Pairs with ./<name>.ts (the TypeScript interface).\n';

function pascalCase(name: string): string {
  const segments = name.split(/[^A-Za-z0-9]+/).filter((s) => s.length > 0);
  if (segments.length === 0) return name;
  return segments.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join('');
}

function refName(ref: string | undefined): string | undefined {
  if (!ref) return undefined;
  const match = /#\/components\/schemas\/(.+)$/.exec(ref) ?? /#\/schemas\/(.+)$/.exec(ref);
  return match?.[1];
}

interface EmissionContext {
  readonly schemas: Readonly<Map<string, SchemaContract>>;
  /** Self-reference (to avoid emitting `<name>Schema` recursively). */
  readonly currentName?: string;
}

/** Emit a Zod expression for a JSON Schema node. */
function emitZod(node: JsonSchemaNode | undefined, ctx: EmissionContext): string {
  if (!node) return 'z.unknown()';

  if (node.$ref) {
    const name = refName(node.$ref);
    if (!name) return 'z.unknown()';
    return `${pascalCase(name)}Schema`;
  }

  if (node.oneOf && node.oneOf.length > 0) {
    const members = node.oneOf.map((child) => emitZod(child, ctx));
    return `z.union([${members.join(', ')}])`;
  }
  if (node.anyOf && node.anyOf.length > 0) {
    const members = node.anyOf.map((child) => emitZod(child, ctx));
    return `z.union([${members.join(', ')}])`;
  }
  if (node.allOf && node.allOf.length > 0) {
    const members = node.allOf.map((child) => emitZod(child, ctx));
    if (members.length === 1) return members[0] ?? 'z.unknown()';
    return members.reduce((acc, m) => `z.intersection(${acc}, ${m})`);
  }

  if (node.enum && node.enum.length > 0) {
    const stringValues = node.enum.filter((v) => typeof v === 'string') as string[];
    if (stringValues.length === node.enum.length) {
      return `z.enum([${stringValues.map((v) => JSON.stringify(v)).join(', ')}])`;
    }
    // Mixed-type enum — emit as union of literals.
    const literals = node.enum
      .map((v) => {
        if (v === null) return 'z.null()';
        if (typeof v === 'string') return `z.literal(${JSON.stringify(v)})`;
        if (typeof v === 'number') return `z.literal(${v})`;
        if (typeof v === 'boolean') return `z.literal(${v ? 'true' : 'false'})`;
        return 'z.unknown()';
      })
      .join(', ');
    return `z.union([${literals}])`;
  }

  const type = node.type;
  switch (type) {
    case 'string':
      return 'z.string()';
    case 'integer':
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'null':
      return 'z.null()';
    case 'array':
      return node.items ? `z.array(${emitZod(node.items, ctx)})` : 'z.array(z.unknown())';
    case 'object':
      return emitObjectSchema(node, ctx);
    default:
      if (node.properties) return emitObjectSchema(node, ctx);
      if (node.additionalProperties === true) return 'z.record(z.unknown())';
      if (node.additionalProperties && typeof node.additionalProperties === 'object') {
        return `z.record(${emitZod(node.additionalProperties, ctx)})`;
      }
      return 'z.unknown()';
  }
}

function emitObjectSchema(node: JsonSchemaNode, ctx: EmissionContext): string {
  const props = node.properties ?? {};
  const required = new Set(node.required ?? []);
  const lines: string[] = ['z.object({'];

  for (const [propName, propSchema] of Object.entries(props)) {
    const base = emitZod(propSchema, ctx);
    const expr = required.has(propName) ? base : `${base}.optional()`;
    lines.push(`  ${JSON.stringify(propName)}: ${expr},`);
  }

  lines.push('})');

  const addl = node.additionalProperties;
  if (addl === true) {
    lines.push('.catchall(z.unknown())');
  } else if (addl && typeof addl === 'object') {
    lines.push(`.catchall(${emitZod(addl, ctx)})`);
  }

  return lines.join('\n');
}

/** Emit one Zod schema file. */
function emitSchemaFile(schema: SchemaContract, ctx: EmissionContext): EmittedFile {
  const name = pascalCase(schema.name);
  const def = schema.definition;
  if (!def) {
    return {
      path: `src/generated/models/${name}.schema.ts`,
      content: `${HEADER}\nimport { z } from 'zod';\n\nexport const ${name}Schema = z.unknown();\n`,
    };
  }

  // Collect external schema refs for the import block.
  const refs = new Set<string>();
  collectRefs(def, refs, schema.name);
  const externalRefs = [...refs].filter((r) => r !== schema.name).sort();
  const importBlock =
    externalRefs.length > 0
      ? externalRefs
          .map((r) => `import { ${pascalCase(r)}Schema } from './${pascalCase(r)}.schema.js';`)
          .join('\n') + '\n'
      : '';

  const expr = emitZod(def, { ...ctx, currentName: schema.name });
  const description = schema.description ? `/** ${schema.description} */\n` : '';

  return {
    path: `src/generated/models/${name}.schema.ts`,
    content: `${HEADER}\nimport { z } from 'zod';\n${importBlock}\n${description}export const ${name}Schema = ${expr};\n`,
  };
}

/** Walk a schema node collecting every $ref target name reachable. */
function collectRefs(node: JsonSchemaNode | undefined, acc: Set<string>, self: string): void {
  if (!node) return;
  if (node.$ref) {
    const name = refName(node.$ref);
    if (name && name !== self) acc.add(name);
    return;
  }
  if (node.properties) {
    for (const prop of Object.values(node.properties)) collectRefs(prop, acc, self);
  }
  if (node.items) collectRefs(node.items, acc, self);
  if (node.oneOf) for (const child of node.oneOf) collectRefs(child, acc, self);
  if (node.anyOf) for (const child of node.anyOf) collectRefs(child, acc, self);
  if (node.allOf) for (const child of node.allOf) collectRefs(child, acc, self);
  if (node.additionalProperties && typeof node.additionalProperties === 'object') {
    collectRefs(node.additionalProperties as JsonSchemaNode, acc, self);
  }
}

/** Emit a barrel `schemas.ts` re-exporting every generated schema. */
function emitSchemasIndex(schemas: readonly SchemaContract[]): EmittedFile {
  const lines = schemas
    .map((s) => `export { ${pascalCase(s.name)}Schema } from './${pascalCase(s.name)}.schema.js';`)
    .sort();
  return {
    path: 'src/generated/models/schemas.ts',
    content: `${HEADER}\n${lines.join('\n')}\n`,
  };
}

/** Emit every Zod schema file + the index. */
export function emitZodSchemas(schemas: readonly SchemaContract[]): readonly EmittedFile[] {
  const lookup = new Map(schemas.map((s) => [s.name, s] as const));
  const ctx: EmissionContext = { schemas: lookup };
  const files = schemas.map((s) => emitSchemaFile(s, ctx));
  files.push(emitSchemasIndex(schemas));
  return files;
}
